PSDI-UK/aiida-gromacs

.coveragerc, .github/check_version.py, .github/install_aiida_github.sh, .github/workflows/ci.yml, .github/workflows/publish-on-pypi.yml, .pre-commit-config.yaml
Added in the github actions now I understand how to use them
=> Add the GitHub actions

aiida_gromacs/calculations/generalMD.py, aiida_gromacs/cli/launch.py, aiida_gromacs/parsers/generalMD.py, examples/gromacs-jobs.sh, examples/gromacs_files/1AKI_clean.pdb, examples/gromacs_files/ions.mdp, examples/gromacs_files/min.mdp, examples/gromacs_files/npt.mdp, examples/gromacs_files/nvt.mdp, examples/gromacs_files/prod.mdp, pyproject.toml
Included a general-MD calculation and parser, with a cli script launch.py to run an AiiDA process that is general to any MD code. An example of running the first 7 stages of gromacs commands with general-MD is also included in examples/gromacs-jobs.sh.
=> General md

.github/workflows/ci.yml
Let's see if this works first time!
=> add coveralls to CI

README.md, docs/source/developer_guide/index.rst, docs/source/index.rst, docs/source/user_guide/get_started.rst
This isn't the final docs, but it makes sense to update to something more recent than the cookie cutter outputs.
=> Pull in some docs

aiida_gromacs/cli/grompp.py
=> automate collection of itp from topology when position restraints are on

aiida_gromacs/cli/createarchive.py, aiida_gromacs/cli/generalMD.py, aiida_gromacs/parsers/generalMD.py, aiida_gromacs/utils/searchprevious.py, pyproject.toml, tests/test_calcs_generalMD.py, tests/test_utils_searchprevious.py
=> tests added for utils

.gitignore, docs/source/user_guide/aiida_sessions.rst, docs/source/user_guide/installation.rst
=> 45 add to aiida session docs

aiida_gromacs/utils/searchprevious.py, tests/test_calcs_genericMD.py, tests/test_utils_searchprevious.py
=> moved functions used only in tests

aiida_gromacs/calculations/genericMD.py, aiida_gromacs/cli/genericMD.py, aiida_gromacs/parsers/genericMD.py, aiida_gromacs/utils/inspectdb.py, aiida_gromacs/utils/querydb.py, pyproject.toml, tests/test_calcs_genericMD.py, tests/test_utils_searchprevious.py
=> changed genericMD entry point to gromacs.genericMD

.github/workflows/ci.yml
=> update CI action versions.

.github/install_aiida_github.sh, .github/workflows/ci.yml
=> Fix tests in CI

aiida_gromacs/calculations/mdrun.py, aiida_gromacs/parsers/mdrun.py, aiida_gromacs/utils/fileparsers.py, tests/test_calcs_mdrun.py
Added logfile parser for extracting metadata, added extra checks in calcs mdrun tests for outputted dictionary node
=> Issue101 add metadata parsers

.github/workflows/publish-on-pypi.yml, README.md, docs/source/developer_guide/index.rst, docs/source/index.rst, pyproject.toml
Move this repository from personal repo to PSDI org repo.
=> transfer repo

.github/workflows/auto-generate-release.yml, .github/workflows/publish-on-pypi.yml
=> Ci auto release

.github/workflows/publish-on-pypi.yml, README.md, docs/source/developer_guide/index.rst, docs/source/index.rst, pyproject.toml
=> migrate repository to PSDI-UK

aiida_gromacs/calculations/genion.py, aiida_gromacs/cli/genion.py, aiida_gromacs/data/genion.py
…run genion
genion can be run with any interactive instructions by providing a text file for each interactive response on a new line.
=> 137 gmx genion uses hard coded solvent

.github/workflows/publish-on-pypi.yml
=> Changes to CI action for autoupdating version numbers

.github/workflows/auto-release.yml
=> change CI workflow

.pre-commit-config.yaml, pyproject.toml, tests/test_utils_searchprevious.py
Changed versions of the CI tools to latest versions.
Also fixed a pre-commit error complaining about variable use before referencing in one of the tests.
=> changed some versions of tools

docs/source/tutorials/genericMD.rst, docs/source/tutorials/lysozyme.rst, docs/source/user_guide/aiida_cheatsheet.rst, docs/source/user_guide/aiida_sessions.rst, docs/source/user_guide/cli_interface.rst, docs/source/user_guide/installation.rst
Updated installation and lysozyme tutorial docs.
=> 151 improve docs

docs/source/user_guide/installation.rst
Ensure python version is 3.11 during Aiida installation
=> Ensure python version is 3.11

docs/source/tutorials/PTH2R_CGMD.rst
Updated variables for PTH2R_coarse-grained tutorial (added $ signs and removed {})
=> Update tutorial variables

.github/workflows/ci.yml
docs are throwing errors. Not sure if something related to python version so put to latest first to rule out.
=> Update python in CI
